### ISSUE TITLE
XML Numeric Values

### ISSUE THREAD

**Issue by Ganbin** [ThomasMaul/Tools_TM#5]
Hello,

When converting XML to Object, every value is stored as `Text`.

I wonder if it would be possible to have the `Tools_XMLToObject` method to be able to parse the XML value as numeric. Ex: 
```
<debit>123.12</debit>
```

Today we would get something like:
```
{
  "__name": "debit",
  "__value": "123.12"
}
```

Would be nice to have 
```
{
  "__name": "debit",
  "__value": 123.12
}
```

Thank you.

**Comment by ThomasMaul** [comment]
I don't know the content type when reading/parsing XML. Trying if a content could be converted to number might work sometimes, but it also might be text (containing a number, date, etc).
That's why it is always text.

**Comment by Ganbin** [comment]
A Regex could do the trick?

**Comment by Ganbin** [comment]
Or maybe it is up to us to parse again the object.

**Comment by ThomasMaul** [comment]
Regex will not really help, it is still guessing...
It is like if you use Excel to open a file. I assume you know the case when their is a column with content such as 01234, which is then handled as number 1234 and the missing 0, which could be important data, is remove. Or numbers with dots or dashes handled as date, while it is a string.
Guessing on content is risky. If you know the type based on the tag/name, then you can convert...
It would require a feature request for another XML DOM command, returning information about the content, such as type or raw data. With the available commands the content is always converted fitting to the given variable, so I need to give a string.
